EmployeeManagement/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;



public class DepartmentController : Controller
{

    public IActionResult index()
    {
        var departments = Department.GetDepartments();
        return View(departments);
    }

}

EmployeeManagement/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using EmployeeManagement.data;
public class  EmployeeController : Controller
{
    // creating database instance 
        private readonly EMSContext db;     
        public EmployeeController(EMSContext _db)
        {
            db = _db;
        }

    // this is action for website
    public IActionResult index()                   
    {                                            
        // var db = new EMSContext();     // creating the database instance 
        var employees = db.Employees.ToList();       // Retriving all the data from Employees table from database 
        return View(employees);
        
    }

    // another action added with name  detail
    //  here the value of the argument is taken through get method because by default the action is in http get method 
    public IActionResult Detail(int id)  
    {
             var employees = db.Employees.ToList(); 
             var employee=employees.FirstOrDefault(x=>x.Id==id);

        return View(employee); // mvc prodgram will search for the cshtml file same name as view() method parameter in views folder under the same name as controller 
                        // if there is no parameter it will search same name as action name 
    
    }
    public IActionResult addEmployee() // default http method request or respose is get 
    {
        return View();
    }

    [HttpPost]   // setting the upcomming action request method to post method 
   
    public IActionResult addEmployee([FromForm]Employee employee)
    {
           db.Employees.Add(employee);
           db.SaveChanges();
           return RedirectToAction("Index");
    }
    [HttpGet]
    public IActionResult DeleteEmp(int id) // here parameter firstName is obtain thorough url
    {
            var employees = db.Employees.ToList();
            var employee=employees.FirstOrDefault(x=>x.Id==id);
                // delete query
                db.Employees.Remove(employee);
                db.SaveChanges();
               return RedirectToAction("Index");

    }

  

      // for update contex
      public IActionResult UpdateEmp(int id)
    {
          var employees = db.Employees.ToList(); 
             var employee=employees.FirstOrDefault(x=>x.Id==id);

            return View(employee);
    } 
    [HttpPost]
    public IActionResult UpdateEmp([FromForm]Employee employee)
    {
            db.Employees.Attach(employee);
            db.Employees.Update(employee);  // update equery
            db.SaveChanges();

            
         
        return RedirectToAction("Index");
    }

   
}

EmployeeManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmployeeManagement</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <!-- here in asp controller name of controller and in asp=action name of the cshtml page located at views folder i.e action -->

                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Employee
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employee"
                                    asp-action="index">Employee list</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employee"
                                    asp-action="addEmployee">Add Employee</a>
                                <div class="dropdown-divider"></div>

                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Department"
                                asp-action="index">Department</a>
                        </li>


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EmployeeManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    



    @RenderSection("Scripts", required: false)
</body>

</html>